name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up build environment
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo apt-get install build-essential
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          brew install automake autoconf # Add any other dependencies
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          choco install mingw
        fi

    - name: Configure
      run: ./configure

    - name: Make
      run: make

    - name: Make Check
      run: make check

    - name: Make Distcheck
      run: make distcheck
