name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [64]
        include:
          - os: macos-latest
            arch: arm

    steps:
      - uses: actions/checkout@v4

      - name: Create Directories
        run: |
          mkdir -p build
          mkdir -p obj
        shell: bash

      - name: Build
        run: make ARCH=${{ matrix.arch }}

      - name: Create Distribution Package
        run: make distcheck ARCH=${{ matrix.arch }}

      - name: Upload Distribution Package
        uses: actions/upload-artifact@v3
        with:
          name: 8086emu_${{ matrix.arch }}_${{ matrix.os }}
          path: build/8086emu_${{ matrix.arch }}_${{ matrix.os }}.zip
