name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Uncomment for releases on tags:
  # release:
  #   types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: 64
            executable: 8086emu
          - os: macos-latest
            arch: 64
            executable: 8086emu
          - os: macos-latest
            arch: arm
            executable: 8086emu
          - os: windows-latest
            arch: 64
            executable: 8086emu.exe

    steps:
      - uses: actions/checkout@v4

      - name: Setup Build Environment (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          # Install MinGW-w64 for g++
          choco install mingw -y
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH
        shell: powershell

      - name: Setup Build Environment (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          # Ensure Xcode command line tools are available
          xcode-select --install || true

      - name: Create Directories
        run: |
          mkdir -p build
          mkdir -p obj
          mkdir -p obj/instructions
        shell: bash

      - name: Build Project
        run: make ARCH=${{ matrix.arch }}
        shell: bash

      - name: Test Build
        run: |
          if [ -f "build/${{ matrix.executable }}" ]; then
            echo "Build successful: build/${{ matrix.executable }}"
            ls -la build/
          else
            echo "Build failed: executable not found"
            exit 1
          fi
        shell: bash

      - name: Create Distribution Package
        run: make distcheck ARCH=${{ matrix.arch }}
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 8086emu-${{ matrix.arch }}-${{ runner.os }}
          path: |
            build/${{ matrix.executable }}
            samples/
            README.md
            *.md

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Set Release Info
        id: release_info
        run: |
          TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          RELEASE_TAG="build-${TIMESTAMP}-${SHORT_SHA}"
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
          echo "RELEASE_NAME=8086 Emulator Build ${TIMESTAMP}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: true
          body: |
            ## 8086 Emulator Build
            
            **Commit:** ${{ github.sha }}
            **Date:** $(date +'%Y-%m-%d %H:%M:%S UTC')
            
            ### Features
            - Complete 8086 instruction set emulation
            - Modular architecture with separate instruction categories
            - Enhanced features: memory operands, REP prefixes, I/O simulation
            - Comprehensive test samples (25 samples from beginner to expert)
            
            ### Downloads
            Choose the appropriate build for your platform:
            - **Linux (x64)**: `8086emu-64-Linux`
            - **macOS (x64)**: `8086emu-64-macOS` 
            - **macOS (ARM)**: `8086emu-arm-macOS`
            - **Windows (x64)**: `8086emu-64-Windows`
            
            ### Usage
            1. Download and extract the appropriate package
            2. Run `./8086emu` (Linux/macOS) or `8086emu.exe` (Windows)
            3. Try the sample files in the `samples/` directory
            4. Use `?` command for help
            
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}