name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [32, 64]
        include:
          - os: macos-latest
            arch: 64
          - os: macos-latest
            arch: arm
          - os: ubuntu-latest
            arch: 32
          - os: ubuntu-latest
            arch: 64
          - os: windows-latest
            arch: 32
          - os: windows-latest
            arch: 64

    steps:
      - uses: actions/checkout@v4

      - name: Create Directories
        run: |
          mkdir -p build
          mkdir -p obj
        shell: bash

      - name: Install Dependencies
        if: matrix.os == 'ubuntu-latest' && matrix.arch == '32'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-multilib

      - name: Build
        run: make ARCH=${{ matrix.arch }}
        
      - name: Create Distribution Package
        run: make distcheck ARCH=${{ matrix.arch }}
