name: Make and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [64]
        include:
          - os: macos-latest
            arch: arm

    steps:
      - uses: actions/checkout@v4

      - name: Create Directories
        run: |
          mkdir -p build
          mkdir -p obj
        shell: bash

      - name: Build
        run: make ARCH=${{ matrix.arch }}

      - name: Create Distribution Package
        run: make distcheck ARCH=${{ matrix.arch }}

      - name: Upload Distribution Package
        uses: actions/upload-artifact@v4
        with:
          name: 8086emu_${{ matrix.arch }}_${{ matrix.os }}
          path: build/8086emu_${{ matrix.arch }}_${{ matrix.os }}.zip

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: 8086emu_${{ matrix.arch }}_${{ matrix.os }}

      - name: Set up Git
        run: |
          git config --global user.name "Saeed Khatami"
          git config --global user.email "saeed.khatami.99@gmail.com"

      - name: Clone Target Repository
        run: |
          git clone https://github.com/saeedkhatami/8086emu-bin.git
          cd 8086emu-bin
          mkdir -p artifacts

      - name: Copy Files
        run: |
          cp 8086emu_${{ matrix.arch }}_${{ matrix.os }}.zip 8086emu-bin/
          cd 8086emu-bin
          git add artifacts
          git commit -m "Add new artifacts for ${{ matrix.arch }} on ${{ matrix.os }}"
          git push

        env:
          REPO_URL: https://saeedkhatami:${{ secrets.TARGET_REPO_PAT }}@github.com/saeedkhatami/8086emu-bin.git

      - name: Push Changes
        run: |
          cd 8086emu-bin
          git remote set-url origin $REPO_URL
          git push
