name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [32, 64]

    steps:
      - uses: actions/checkout@v4
      
      - name: Create Directories
        run: |
          mkdir -p build
          mkdir -p obj
        shell: bash

      - name: Build
        run: make ARCH=${{ matrix.arch }}
      - name: Create Distribution Package
        run: make distcheck ARCH=${{ matrix.arch }}
