name: Make and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [64]
        include:
          - os: macos-latest
            arch: arm

    steps:
      - uses: actions/checkout@v4

      - name: Create Directories
        run: |
          mkdir -p build
          mkdir -p obj
        shell: bash

      - name: Build
        run: make ARCH=${{ matrix.arch }}

      - name: Create Distribution Package
        run: make distcheck ARCH=${{ matrix.arch }}

      - name: Upload Distribution Package
        uses: actions/upload-artifact@v4
        with:
          name: 8086emu_${{ matrix.arch }}_${{ matrix.os }}
          path: build/8086emu_${{ matrix.arch }}_${{ matrix.os }}.zip

      - name: Clone Target Repository
        run: |
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/saeedkhatami/8086emu-bin.git
          cd 8086emu-bin
          git config user.name "Saeed Khatami"
          git config user.email "saeed.khatami.99@gmail.com"

      - name: Copy and Commit Artifacts
        run: |
          cp build/8086emu_${{ matrix.arch }}_${{ matrix.os }}.zip 8086emu-bin/
          cd 8086emu-bin
          git add 8086emu_${{ matrix.arch }}_${{ matrix.os }}.zip
          git commit -m "Add new artifacts for ${{ matrix.arch }} on ${{ matrix.os }}"
          git pull --rebase origin main
          git push origin main --force
