name: Make and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [64]
        include:
          - os: macos-latest
            arch: arm

    steps:
      - uses: actions/checkout@v4

      - name: Create Directories
        run: |
          mkdir -p build
          mkdir -p obj
        shell: bash

      - name: Build
        run: make ARCH=${{ matrix.arch }}

      - name: Create Distribution Package
        run: make distcheck ARCH=${{ matrix.arch }}

      - name: Upload Distribution Package
        uses: actions/upload-artifact@v4
        with:
          name: 8086emu_${{ matrix.arch }}_${{ matrix.os }}
          path: build/8086emu_${{ matrix.arch }}_${{ matrix.os }}.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-upload
    steps:
      - name: Set up Git
        run: |
          git config --global user.name "Saeed Khatami"
          git config --global user.email "saeed.khatami.99@gmail.com"

      - name: Clone Target Repository
        run: |
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/saeedkhatami/8086emu-bin.git
          cd 8086emu-bin
          git config user.name "Saeed Khatami"
          git config user.email "saeed.khatami.99@gmail.com"

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: 8086emu-bin/artifacts

      - name: Copy Artifacts to Root
        run: |
          cd 8086emu-bin
          cp artifacts/* .  # Copy all artifacts to the root of the repository
          git add .
          git commit -m "Add new artifacts from all builds"

      - name: Push Changes
        run: |
          cd 8086emu-bin
          git pull --rebase origin main

          n=0
          until [ "$n" -ge 5 ]
          do
            git push origin main && break
            n=$((n+1))
            echo "Push failed, retrying in 5 seconds... ($n)"
            sleep 5
          done
